In [1]:
import pyspark.sql.functions as F

from src.spark_session import get_spark
from src.utils.display_mimic import display

spark = get_spark()

Warning: Ignoring non-Spark config property: javax.jdo.option.ConnectionURL

:: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /root/.ivy2/cache
The jars for the packages stored in: /root/.ivy2/jars
io.delta#delta-spark_2.12 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-fd6995a0-7ba4-4752-b939-713bed0a7cb4;1.0
	confs: [default]
	found io.delta#delta-spark_2.12;3.0.0 in central
	found io.delta#delta-storage;3.0.0 in central
	found org.antlr#antlr4-runtime;4.9.3 in central
downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.0.0/delta-spark_2.12-3.0.0.jar ...
	[SUCCESSFUL ] io.delta#delta-spark_2.12;3.0.0!delta-spark_2.12.jar (659ms)
downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.0.0/delta-storage-3.0.0.jar ...
	[SUCCESSFUL ] io.delta#delta-storage;3.0.0!delta-storage.jar (86ms)
downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
	[SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (89ms)
:: resolution report :: resolve 3320ms :: artifacts dl 863ms
	:: modules in use:
	io.delta#delta-spark_2.12;3.0.0 from central in [default]
	io.delta#delta-storage;3.0.0 from central in [default]
	org.antlr#antlr4-runtime;4.9.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   3   |   3   |   0   ||   3   |   3   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-fd6995a0-7ba4-4752-b939-713bed0a7cb4
	confs: [default]
	3 artifacts copied, 0 already retrieved (5230kB/41ms)
26/03/05 23:23:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

In [2]:
df_publish_products = spark.table('publish.publish_products')

26/03/05 23:23:32 WARN HiveConf: HiveConf of name hive.stats.jdbc.timeout does not exist
26/03/05 23:23:32 WARN HiveConf: HiveConf of name hive.stats.retries.wait does not exist
26/03/05 23:23:38 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 2.3.0
26/03/05 23:23:38 WARN ObjectStore: setMetaStoreSchemaVersion called but recording version is disabled: version = 2.3.0, comment = Set by MetaStore UNKNOWN@172.18.0.2
26/03/05 23:23:39 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException

In [8]:
display(df_publish_products.filter(F.col('Color').isNull()))

Empty DataFrame
Columns: [ProductID, ProductDesc, ProductNumber, MakeFlag, Color, SafetyStockLevel, ReorderPoint, Size, SizeUnitMeasureCode, WeightUnitMeasureCode, StandardCost, ListPrice, Weight, ProductCategoryName, ProductSubCategoryName, loaded_at]
Index: []

In [16]:
display(df_publish_products.filter(F.col('Color') == 'N/A'), 10)

,ProductID,ProductDesc,ProductNumber,MakeFlag,Color,SafetyStockLevel,ReorderPoint,Size,SizeUnitMeasureCode,WeightUnitMeasureCode,StandardCost,ListPrice,Weight,ProductCategoryName,ProductSubCategoryName,loaded_at
0,802,LL Fork,FK-1639,True,N/A,500,375,None,None,None,65.81,148.22,None,None,Forks,2026-03-05 23:20:13.966909
1,803,ML Fork,FK-5136,True,N/A,500,375,None,None,None,77.92,175.49,None,None,Forks,2026-03-05 23:20:13.966909
2,804,HL Fork,FK-9939,True,N/A,500,375,None,None,None,101.89,229.49,None,None,Forks,2026-03-05 23:20:13.966909
3,805,LL Headset,HS-0296,True,N/A,500,375,None,None,None,15.18,34.20,None,Accessories,Headsets,2026-03-05 23:20:13.966909
4,806,ML Headset,HS-2451,True,N/A,500,375,None,None,None,45.42,102.29,None,Accessories,Headsets,2026-03-05 23:20:13.966909
5,807,HL Headset,HS-3479,True,N/A,500,375,None,None,None,55.38,124.73,None,Accessories,Headsets,2026-03-05 23:20:13.966909
6,808,LL Mountain Handlebars,HB-M243,True,N/A,500,375,None,None,None,19.78,44.54,None,Accessories,Handlebars,2026-03-05 23:20:13.966909
7,809,ML Mountain Handlebars,HB-M763,True,N/A,500,375,None,None,None,27.49,61.92,None,Accessories,Handlebars,2026-03-05 23:20:13.966909
8,810,HL Mountain Handlebars,HB-M918,True,N/A,500,375,None,None,None,53.40,120.27,None,Accessories,Handlebars,2026-03-05 23:20:13.966909
9,811,LL Road Handlebars,HB-R504,True,N/A,500,375,None,None,None,19.78,44.54,None,Accessories,Handlebars,2026-03-05 23:20:13.966909

In [17]:
(
    display(
    df_publish_products
    .filter(F.col("ProductCategoryName").isNull() &
           (F.col("ProductSubCategoryName")
            .isin(
                "Gloves", 
                "Shorts", 
                "Socks", 
                "Tights", 
                "Vests",
                "Locks", 
                "Lights", 
                "Headsets", 
                "Helmets", 
                "Pedals", 
                "Pumps",
                "Wheels", 
                "Saddles")))
            )
)

Empty DataFrame
Columns: [ProductID, ProductDesc, ProductNumber, MakeFlag, Color, SafetyStockLevel, ReorderPoint, Size, SizeUnitMeasureCode, WeightUnitMeasureCode, StandardCost, ListPrice, Weight, ProductCategoryName, ProductSubCategoryName, loaded_at]
Index: []